# preprocess.py — Data Preprocessing and Feature Engineering
#
# Responsibilities:
#   1. Load the pre-processed BBBP.csv (chemical descriptors are generated by dataset/process.py)
#   2. Convert SMILES to 2048-dim Morgan Fingerprint (using dataset/utils.py)
#   3. Concatenate Morgan FP + chemical descriptors → complete feature matrix
#   4. Correlation matrix analysis (for 7 descriptors only), to assist feature selection decisions
#   5. StandardScaler normalization (fit on training set only to prevent data leakage)
#   6. Split train/val/test as 80/10/10 (stratified, SEED=67)
#
# External API:
#   load_and_preprocess() → Returns split data, scaler, test_df, etc.

import os
import sys
import numpy as np  # type: ignore
import pandas as pd  # type: ignore
from sklearn.model_selection import train_test_split  # type: ignore
from sklearn.preprocessing import StandardScaler  # type: ignore
import matplotlib.pyplot as plt  # type: ignore
import seaborn as sns  # type: ignore

# Add project root directory to path for importing dataset package
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from dataset.utils import get_morgan_fingerprint  # type: ignore

# ── Constants ──────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(BASE_DIR, "..", "dataset", "BBBP.csv")
PLOTS_DIR = os.path.join(BASE_DIR, "plots")
SEED = 67

# The 7 chemical descriptor columns present in the CSV
DESCRIPTOR_COLS = ["LogP", "TPSA", "MW", "HBA", "HBD", "RotatableBonds", "Charge"]


def _generate_fingerprints(smiles_series: pd.Series) -> tuple[np.ndarray, list[bool]]:
    """Batch convert SMILES series to 2048-bit Morgan Fingerprint.

    Returns:
        fp_matrix: shape (n_valid, 2048)
        valid_mask: Boolean list of the same length as the original series, marking rows that were successfully converted
    """
    fps = []
    valid_mask = []
    for smiles in smiles_series:
        fp = get_morgan_fingerprint(smiles)
        if fp is not None:
            fps.append(fp)
            valid_mask.append(True)
        else:
            valid_mask.append(False)
    return np.array(fps, dtype=np.float32), valid_mask


def _analyze_correlations(df: pd.DataFrame, save_plot: bool = True) -> pd.DataFrame:
    """Compute Pearson correlation matrix of chemical descriptors to identify highly correlated feature pairs.

    Only analyze the 7 descriptors (Morgan FP is a 2048-d sparse binary vector, not suitable for this analysis).
    """
    corr = df[DESCRIPTOR_COLS].corr()

    print("\n=== Chemical Descriptor Correlation Matrix ===")
    print(corr.to_string())

    # Find descriptor pairs with |r| > 0.85
    high_corr_pairs = []
    for i in range(len(DESCRIPTOR_COLS)):
        for j in range(i + 1, len(DESCRIPTOR_COLS)):
            r = corr.iloc[i, j]
            if abs(r) > 0.85:
                high_corr_pairs.append((DESCRIPTOR_COLS[i], DESCRIPTOR_COLS[j], r))

    if high_corr_pairs:
        print("\nHighly correlated pairs (|r| > 0.85):")
        for f1, f2, r in high_corr_pairs:
            print(f"  {f1} <-> {f2}: r = {r:.3f}")
        print("Consider removing one feature from each pair to reduce redundancy.")
    else:
        print("\nNo feature pairs with |r| > 0.85. All descriptors retained.")

    if save_plot:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        plt.figure(figsize=(8, 6))
        sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
        plt.title("Chemical Descriptor Correlation Matrix")
        plt.tight_layout()
        path = os.path.join(PLOTS_DIR, "correlation_matrix.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"Correlation matrix plot saved to {path}")

    return corr


def load_and_preprocess(
    plot_correlation: bool = False,
) -> dict:
    """Load dataset, generate features, scale, split.

    Returns:
        dict with keys:
            X_train, X_val, X_test       — Standardized feature matrices
            y_train, y_val, y_test        — Labels
            scaler                        — Fitted StandardScaler
            feature_names                 — List of feature column names
            test_df                       — Original DataFrame corresponding to the test set (including smiles, name, etc.)
            correlation_matrix            — Descriptor correlation matrix (only present if plot_correlation=True)
    """
    # 1. Load data, drop rows with NaN
    df = pd.read_csv(CSV).dropna()
    print(f"Loaded {len(df)} samples from {CSV}")

    # 2. SMILES → 2048-bit Morgan Fingerprint
    fp_matrix, valid_mask = _generate_fingerprints(df["smiles"])
    df = df[valid_mask].reset_index(drop=True)
    print(f"Valid fingerprints: {len(df)} / {len(valid_mask)} (dropped {sum(not v for v in valid_mask)})")

    # 3. Extract existing chemical descriptors
    descriptors = df[DESCRIPTOR_COLS].values.astype(np.float32)

    # 4. Correlation matrix analysis (optional)
    corr = None
    if plot_correlation:
        corr = _analyze_correlations(df)

    # 5. Concatenate features: Morgan FP (2048) + descriptors (7) = 2055 dims
    X = np.hstack([fp_matrix, descriptors])
    y = df["p_np"].values
    feature_names = [f"FP_{i}" for i in range(fp_matrix.shape[1])] + DESCRIPTOR_COLS

    # 6. Split by indices 80/10/10, stratified, for reproducibility
    indices = np.arange(len(df))
    idx_trainval, idx_test = train_test_split(
        indices, test_size=0.1, random_state=SEED, stratify=y,
    )
    # Further split val from the remaining 90% (val is 10% of all data, i.e., 1/9 of trainval)
    idx_train, idx_val = train_test_split(
        idx_trainval, test_size=1 / 9, random_state=SEED, stratify=y[idx_trainval],
    )

    X_train, X_val, X_test = X[idx_train], X[idx_val], X[idx_test]
    y_train, y_val, y_test = y[idx_train], y[idx_val], y[idx_test]
    test_df = df.iloc[idx_test].reset_index(drop=True)

    # 7. Standardize: fit only on training set to prevent data leakage
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)
    X_test = scaler.transform(X_test)

    # Summary
    n_pos_train = int(y_train.sum())
    print(f"Split — train: {len(X_train)}, val: {len(X_val)}, test: {len(X_test)}")
    print(f"Feature dim: {X_train.shape[1]}  (2048 Morgan FP + {len(DESCRIPTOR_COLS)} descriptors)")
    print(f"Train class balance: {n_pos_train}/{len(y_train)} positive "
          f"({n_pos_train / len(y_train):.1%})")

    return {
        "X_train": X_train, "X_val": X_val, "X_test": X_test,
        "y_train": y_train, "y_val": y_val, "y_test": y_test,
        "scaler": scaler,
        "feature_names": feature_names,
        "test_df": test_df,
        "correlation_matrix": corr,
    }


# ── Standalone run: validate preprocessing workflow and output correlation matrix ──
if __name__ == "__main__":
    data = load_and_preprocess(plot_correlation=True)
    print("\nPreprocessing complete. Ready for tuning / training.")
